---
Title: "Homework 1"
Subtitle: "Submission 3"
Author: "Alekhya Pidugu"
---
```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, readr, readxl, hrbrthemes, fixest, 
                scales, gganimate, gapminder, gifski, png, tufte, ploty, OECD,
                ggrepel, survey, foreign, devtools, pdftools, kableExtra, modelsummary, knitr)

```
```{r}
#| echo: false
#| label: fig.premium
#| fig-cap: "Share of 0 premium plans"
```
```{r}
install.packages("knitr")
install.packages("kableExtra")

library(knitr)
library(kableExtra)
library(dplyr)
```

```{r}
# Load data from .RData file
load("Submission2/Hwk1_workspace.Rdata")
```
```{r}
#| echo: false 
#| label: tbl-plans 
#| tbl-cap: "Plan types by year"

options(knitr.kable.NA = 0)
knitr::kable(plan_count_table,
            col.names=c("Plan Type", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"), 
            format.args=list(big.mark=","), booktabs = TRUE) %>%
            kable_styling(latex_options=c("scale_down"))
```
